apiVersion: v1
kind: Service
metadata:
  name: heft-scheduler-service
spec:
  selector:
    app: heft-scheduler
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  clusterIP: 10.100.0.214

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heft-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heft-scheduler
  template:
    metadata:
      labels:
        app: heft-scheduler
    spec:
      containers:
      - name: heft-scheduler
        image: 329701247918.dkr.ecr.us-east-1.amazonaws.com/krzysiek-ecr:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
      nodeSelector:
        nodetype: hfmaster